# Generated by Django 5.1.1 on 2025-04-09 11:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('rsa_public_key', models.TextField()),
                ('rsa_private_key_encrypted', models.TextField()),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('uploader', 'Uploader'), ('reviewer', 'Reviewer')], max_length=10)),
            ],
        ),
    ]
