# Generated by Django 5.1.1 on 2025-04-13 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureDocAI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('encrypted_file', models.FileField(upload_to='encrypted/')),
                ('encrypted_aes_key', models.BinaryField()),
                ('encrypted_metadata', models.BinaryField(blank=True, null=True)),
                ('classification', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='SecureDocAI.user')),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_keywords', models.JSONField()),
                ('ai_model_version', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification_result', to='SecureDocAI.document')),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('view', 'View'), ('share', 'Share')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecureDocAI.user')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecureDocAI.document')),
            ],
        ),
    ]
