# Generated by Django 5.1.1 on 2025-04-16 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureDocAI', '0002_document_classificationresult_accesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecureDocAI.document')),
                ('reviewer', models.ForeignKey(limit_choices_to={'role': 'reviewer'}, on_delete=django.db.models.deletion.CASCADE, to='SecureDocAI.user')),
            ],
            options={
                'unique_together': {('reviewer', 'document')},
            },
        ),
    ]
