# Generated by Django 5.1.1 on 2025-04-16 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureDocAI', '0003_reviewrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_aes_key', models.BinaryField()),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecureDocAI.document')),
                ('shared_with', models.ForeignKey(limit_choices_to={'role': 'reviewer'}, on_delete=django.db.models.deletion.CASCADE, to='SecureDocAI.user')),
            ],
            options={
                'unique_together': {('document', 'shared_with')},
            },
        ),
    ]
