# Generated by Django 5.1.1 on 2025-04-17 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureDocAI', '0005_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='action',
            field=models.CharField(choices=[('upload', 'Upload'), ('view', 'View'), ('share', 'Share'), ('download', 'Download'), ('review_request', 'Review Request Sent'), ('review_status', 'Review Status Changed'), ('login', 'Login'), ('logout', 'Logout')], max_length=20),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SecureDocAI.document'),
        ),
    ]
