# Generated by Django 5.1.1 on 2025-05-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureDocAI', '0008_user_failed_login_attempts_user_lockout_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
