# Generated by Django 5.1.1 on 2025-05-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureDocAI', '0009_document_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='action',
            field=models.CharField(choices=[('upload', 'Upload'), ('view', 'View'), ('share', 'Share'), ('download', 'Download'), ('review_request', 'Review Request Sent'), ('review_status', 'Review Status Changed'), ('login', 'Login'), ('logout', 'Logout'), ('delete', 'Delete')], max_length=20),
        ),
    ]
